# Generated by Django 5.2 on 2025-04-03 08:56

import courses.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0005_course_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Konten', 'verbose_name_plural': 'Konten'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'verbose_name': 'Kursus', 'verbose_name_plural': 'Kursus'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'File'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Gambar', 'verbose_name_plural': 'Gambar'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Modul'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Mata Pelajaran', 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Konten Teks', 'verbose_name_plural': 'Konten Teks'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Video'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Status kursus aktif atau tidak'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Siswa yang terdaftar dalam kursus', related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, help_text='Ukuran file dalam bytes', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Teks alternatif untuk aksesibilitas', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durasi video dalam detik', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='provider',
            field=models.CharField(choices=[('YT', 'YouTube'), ('VM', 'Vimeo'), ('OT', 'Other')], default='YT', help_text='Penyedia layanan video', max_length=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(help_text='Jenis konten', limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(help_text='Modul yang memiliki konten ini', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID objek konten'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=courses.fields.OrderField(blank=True, help_text='Urutan konten dalam modul'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(help_text='Deskripsi singkat tentang kursus'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(help_text='Instruktur yang membuat kursus', on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='URL-friendly judul', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='Mata pelajaran yang berkaitan dengan kursus', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Judul kursus', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Upload file (PDF, DOC, XLS, dll)', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(help_text='Pembuat konten ini', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(help_text='Judul konten', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(help_text='Upload gambar (JPG, PNG, GIF)', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(help_text='Pembuat konten ini', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='Judul konten', max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(help_text='Kursus yang memiliki modul ini', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi tentang modul'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, help_text='Urutan modul dalam kursus'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(help_text='Judul modul', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(help_text='URL-friendly judul', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(help_text='Judul mata pelajaran', max_length=200),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(help_text='Isi teks'),
        ),
        migrations.AlterField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(help_text='Pembuat konten ini', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(help_text='Judul konten', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(help_text='Pembuat konten ini', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Judul konten', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='URL video (YouTube, Vimeo, dll)'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'object_id'], name='courses_con_content_440b54_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['order'], name='courses_con_order_53ec53_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created'], name='courses_cou_created_6f51ad_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['-created'], name='courses_fil_created_068c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='courses_ima_created_bf87c8_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['order'], name='courses_mod_order_e9c068_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['slug'], name='courses_sub_slug_dd8f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['-created'], name='courses_tex_created_a47fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created'], name='courses_vid_created_c0236d_idx'),
        ),
    ]
