# Generated by Django 5.2 on 2025-04-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_content_options_alter_course_options_and_more'),
    ]

    operations = [
    ]
